version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
     # build the application image
     - run: docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:$CIRCLE_BRANCH
